language: r
cache: packages

branches:
  only:
  - master

env:
  global:
    - secure: "fNKY7GUlpPfu7rOxeXUsmovs3kl8u8HNhQUiVfq3lshcHDNJVl8WG1KSscP4FdzKwJKJZhEfwQS/ddGXEWKtSDNiNpL7KX6ELK9uIaaupfSw0QHXSUYF5W5FgAo+BiFFCnAh2sbISZ1K9acIYhlIyoGv+4PjqUSwK5/lCD9WI4CrelZT9Is4QPClaFKTgxj5wqoFyHE7aOc/WK4ER8jl680QiV/K1zaQKfi7hiaLpqPW/cNNj5+tCEWypZ7fRyog4nD6n8ZfBEcN3/BcFRmuMBDPQEhzIv+K5rCCn/35fNOuq58EG0rEREqFBIIzZthF8golwAZxTcyTpNuj/kfhqN/E2wRN3J9mtInWYX1v/3L2OTxTP0s5Yr8MQzCxOu5OAOH2rNYBTuDndJKkMgiV8AnsGJKlmEPOWl/DDMe64GBe41iCcRZmxC2mP863osXmhSGqD6XO6Dx4PK/7a280giEGvagJX2I8kp1wgxK+0oa2spUoZ0uS2ovMSaMsNl6dS//4olgwzp0V3XUVcs62zxXuutXytfHx99Fn5Ae4wMFJo88XJC3/h07aXfn+oacxXW2Oi0DTYFSan9A96hO15P1NeTa4GsPDHDuWFIg6pMKLqAGP+kiY9MjZtM96s0A4AK5BBDQvihm3zXoBevPpk7hRgr+Ytd5JFYmqZCV/b6w="
